Clin 452
Ferlab-Ste-Justine/clin-ui pull request #10
Opened 2021-11-19 16:54 UTC by oliviercperrier

![image](https://user-images.githubusercontent.com/28421005/142661117-0061d56f-8c49-430d-8d31-3711f1b2d83d.png)

2021-11-22 19:32 UTC, francisl requested changes
Les traductions sont importantes pour ce projet

2021-11-22 19:32 UTC, francisl commented on src/components/Results/ServerError.tsx
> +}: OwnProps) => <Result status="500" title={title} subTitle={description} />;
nous allons devoir faire fonctionner les traductions.

2021-11-22 19:32 UTC, francisl commented on src/store/graphql/variants/queries.tsx
> +            #participant_frequency
effacer?

2021-11-22 19:32 UTC, francisl commented on src/views/screens/variant/Entity/ResumePanel/Summary/index.tsx
> +              <Text className={styles.infoTitle}>Start</Text>
il va falloir des traductions pour tout ca.

2021-11-22 19:32 UTC, francisl commented on src/views/screens/variant/Entity/ResumePanel/index.module.scss
> +@import "../../../../../style/themes/clin/colors";
absolute

2021-11-23 14:30 UTC, oliviercperrier commented on src/components/Results/ServerError.tsx
> +}: OwnProps) => <Result status="500" title={title} subTitle={description} />;
Yes je les ai rajouté, j'ai fait la PR mais je suis encore entrain de travailler dessus

2021-11-24 16:08 UTC, francisl requested changes

2021-11-24 16:08 UTC, francisl commented on src/views/screens/variant/Entity/ClinicalPanel/columns.tsx
> +          <>
Je pense que ce code serait plus lisible avec un switch et des composante séparé, même si ils sont petit.

2021-11-24 16:08 UTC, francisl commented on src/views/screens/variant/Entity/ClinicalPanel/utils.tsx
> +      };
je crois que ca serait mieux d'avoir des fonctions qui retour le default et retirer de cette 'grosse' fonction le `if fest`.
```javascript
let rowOrphanet = orphanetFromEdges(orphanetEdges)
```
ou mieux

2021-11-24 16:08 UTC, francisl commented on src/views/screens/variant/Entity/PatientPanel/index.tsx
> +  return donors?.map((donor: ArrangerEdge<DonorsEntity>, index) => ({
no return if no need

2021-11-24 19:33 UTC, francisl requested changes
stp fixé les `any`

Ce que je vois, seule ceux dans `store/graphql` peuvent se justifier

2021-11-24 20:42 UTC, oliviercperrier commented on src/store/graphql/utils/query.ts
> +  TData = any,
meme chose ici

2021-11-24 20:42 UTC, oliviercperrier commented on src/store/graphql/utils/query.ts
> +export const useLazyResultQueryOnLoadOnly = <
et ici

2021-11-24 20:42 UTC, oliviercperrier commented on src/utils/helper.ts
> +export const isNumber = (n: any) => n && !Number.isNaN(n);
ici aussi

2021-11-24 20:42 UTC, oliviercperrier commented on src/views/screens/variant/Entity/ClinicalPanel/utils.tsx
> +export const groupRowsBySource = (ungroupedDataTable: any[]) => {
J'ai essayé de réglé celui-ci mais les types changes tellement que ca devient compliqué. (En passant c'est un bout de code que j'ai repris de kids first)

2021-11-25 17:17 UTC, merged