Clin-666: fix export nanuq pour status autre que approuvé
Ferlab-Ste-Justine/clin-ui pull request #100
Opened 2022-01-10 20:03 UTC by claudia1296

Ne plus permettre l'export Nanuq lorsqu'on a sélectionner une prescription qui n'est pas approuvée

2022-01-10 20:07 UTC, oliviercperrier commented on src/views/screens/search/table/NanuqModal.tsx
> +import { Typography } from 'antd';
Normalement on met une majuscule seulement dans le cas ou on retourne une class ou component. À moins que cette config est utilisée a d'autre endroit que dans Prescription table, je la metterais juste directement dans Modal.error([...])

2022-01-10 20:08 UTC, oliviercperrier requested changes

2022-01-10 20:08 UTC, oliviercperrier commented on src/views/screens/search/table/NanuqModal.tsx
> +      <div className="nanuq-modal__content">
Il faudrait utiliser les module.scss pour le style

2022-01-10 21:21 UTC, francisl commented on src/views/screens/search/table/NanuqModal.tsx
> +import { Typography } from 'antd';
pour le nom de fichier?

2022-01-10 23:00 UTC, oliviercperrier commented on src/views/screens/search/table/NanuqModal.tsx
> +import { Typography } from 'antd';
Oui

2022-01-11 19:39 UTC, claudia1296 commented on src/views/screens/search/table/NanuqModal.tsx
> +      <div className="nanuq-modal__content">
c'est un mauvais copier coller il y a pas de style en fait, J'ai corrigé

2022-01-11 19:42 UTC, evans-g-crsj approved these changes

2022-01-11 19:43 UTC, merged