fix: #CLIN-500 add padding in content header, add patientId cell link
Ferlab-Ste-Justine/clin-ui pull request #17
Opened 2021-11-25 01:50 UTC by francisl

<img width="1224" alt="Screen Shot 2021-11-24 at 4 57 52 PM" src="https://user-images.githubusercontent.com/98903/143358822-817ba567-7556-402c-86be-edac8ff34985.png">

2021-11-25 03:11 UTC, oliviercperrier commented on src/components/Layout/Content/Header.tsx
> +  <div className={styles.contentHeader}>
@francisl  Tu pourrais remplacer ContentHeader par un PageHeader (https://ant.design/components/page-header/) 

Tu n'aurais plus besoin de ContentHeader.tsx et de Content/Header.tsx

`<PageHeader title={title} />`

2021-11-25 03:11 UTC, oliviercperrier commented on src/components/Layout/Content/Header.tsx
> +  <div className={styles.contentHeader}>
Je l'utilise dans la page de variant entity

2021-11-25 03:13 UTC, oliviercperrier commented on src/views/screens/search/PatientsPrescriptions.tsx
> +      <ContentHeader title={intl.get("screen.patientsearch.title")} />
```suggestion
    import { PageHeader } from "antd";

    [...]

    <PageHeader title={intl.get("screen.patientsearch.title")} />
```

2021-11-25 03:24 UTC, oliviercperrier requested changes
Tu pourrais utiliser PageHeader de antd au lieu de ton custom ContentHeader ca ferais du code en moins

2021-11-25 21:46 UTC, francisl commented on src/components/Layout/Content/Header.tsx
> +  <div className={styles.contentHeader}>
c'est pas le header de la base, juste la bare blanche du contenu

2021-11-25 21:47 UTC, francisl commented on src/views/screens/search/PatientsPrescriptions.tsx
> +      <ContentHeader title={intl.get("screen.patientsearch.title")} />
a moin que je me trompe, mais le `PageHeader` est pour la page au complet. celui la, c'est juste pour le `patient et prescription` en haut du contenu, en dessous de l'autre 'PageHeader'

2021-11-26 04:31 UTC, francisl commented
apres avoir jouer avec je ne vois pas l'intérêt de l'utiliser dans ce context.

1. On n'utilisera pas les options de navigation
2. Il faut que chaque page fournisse sa proper class css ou bien sache laquelle prendre (la solution est de créer un autre composante o_0)
3. Ca demande plus de css que mon composante.

2021-11-26 04:32 UTC, merged