fix: CLIN-846 ajout bouton logout
Ferlab-Ste-Justine/clin-ui pull request #176
Opened 2022-04-12 18:35 UTC by claudia1296

2022-04-12 18:48 UTC, evans-g-crsj requested changes

2022-04-12 18:48 UTC, evans-g-crsj commented on src/utils/user.ts
> +export const logout = () => {
1) pourquoi mettre ce fichier dans `utils` ? De mon point de vue, c'est plus fondamental qu'un utilitaire.
2) ça sert à quoi de mettre un try/catch ici si tout ce qu'on fait est de log l'info?

2022-04-12 18:48 UTC, evans-g-crsj commented on src/components/Layout/Header/index.tsx
> +  return (
enlever le () => { return } et faire directement () => (<Menu ...>)

2022-04-12 18:48 UTC, evans-g-crsj commented on src/components/Layout/Header/index.tsx
> +        <Dropdown overlay={userMenu()} trigger={['click']} key="2">
profites-en pour enlever le `if (userFirstname) ` on faisait ça, car on passait le token via clinfrontend et on avait des problèmes.

2022-04-22 18:29 UTC, oliviercperrier approved these changes

2022-04-25 14:24 UTC, merged